FROM quay.io/keycloak/keycloak:latest

ARG KEYCLOAK_ADMIN
ARG KEYCLOAK_ADMIN_PASSWORD

ARG DB_VENDOR
ARG DB_ADDR
ARG DB_DATABASE
ARG DB_USER
ARG DB_PASSWORD

ENV KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
ENV KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}

ENV DB_VENDOR=${DB_VENDOR}
ENV DB_ADDR=${DB_ADDR}
ENV DB_DATABASE=${DB_DATABASE}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}

COPY ./themes /opt/keycloak/themes

EXPOSE 8080

CMD ["start-dev"]

